branches:
  only:
    - master
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - mkdir $HOME/.mycroft
# command to run tests
script:
  - pytest tests
